# Generated by Django 4.1.7 on 2023-04-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicrosWeb', '0003_alter_a1promociones_contenido_and_more'),
        ('ai03Servicios', '0002_alter_servicios_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='Categoria',
            field=models.ManyToManyField(to='aicrosWeb.a4negocio'),
        ),
    ]
