# Generated by Django 4.1.7 on 2023-04-24 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai01Nosotros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronologia',
            name='autor',
        ),
        migrations.AddField(
            model_name='cronologia',
            name='Periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ai01Nosotros.historia'),
            preserve_default=False,
        ),
    ]
