# Generated by Django 4.1.7 on 2023-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai01Nosotros', '0002_remove_cronologia_autor_cronologia_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronologia',
            name='Contenido',
            field=models.TextField(max_length=100),
        ),
    ]
