# Generated by Django 4.1.7 on 2023-04-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '04Catalogo',
                'verbose_name_plural': '04Catalogos',
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '02Contrato',
                'verbose_name_plural': '02Contratos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '01Documento',
                'verbose_name_plural': '01Documentos',
            },
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '05Otro',
                'verbose_name_plural': '05Otros',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': '03Servicio',
                'verbose_name_plural': '03Servicios',
            },
        ),
    ]
