# Generated by Django 4.1.7 on 2023-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai04Documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogos',
            name='Doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contratos',
            name='Doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='documentos',
            name='Doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='otros',
            name='Doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='servicios',
            name='Doc',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
