# Generated by Django 4.1.7 on 2023-04-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai04Documentos', '0002_catalogos_doc_contratos_doc_documentos_doc_otros_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogos',
            name='Doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='Doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='Doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='otros',
            name='Doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='Doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
