# Generated by Django 4.1.7 on 2023-04-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistribuidoAicros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Contenido', models.TextField(max_length=5000)),
                ('Desarrollo', models.ImageField(upload_to='')),
                ('Logotipo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': '02Distribuido',
                'verbose_name_plural': '02Distribuidos',
            },
        ),
        migrations.CreateModel(
            name='ProductosAicros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Contenido', models.TextField(max_length=5000)),
                ('Desarrollo', models.ImageField(upload_to='')),
                ('Logotipo', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': '01Desarrollado',
                'verbose_name_plural': '01Desarrollados',
            },
        ),
    ]
