# Generated by Django 4.1.7 on 2023-04-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a1Promociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Contenido', models.CharField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Home/Promociones')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promocion',
                'verbose_name_plural': 'Promociones',
            },
        ),
        migrations.CreateModel(
            name='a2Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Contenido', models.CharField(max_length=5000)),
                ('imagen', models.ImageField(upload_to='Home/Productos')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='a3Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Contenido', models.CharField(max_length=5000)),
                ('imagen', models.ImageField(upload_to='Home/Servicios')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='a4Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contenido', models.CharField(max_length=5000)),
                ('imagen', models.ImageField(upload_to='Home/Negocios')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='a5Sifras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Contenido', models.CharField(max_length=5000)),
                ('numero', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sifra',
                'verbose_name_plural': 'Sifras',
            },
        ),
        migrations.CreateModel(
            name='a6Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Contenido', models.CharField(max_length=5000)),
                ('imagen', models.ImageField(upload_to='Home/Noticias')),
                ('Creado', models.DateTimeField(auto_now_add=True)),
                ('Actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticios',
            },
        ),
        migrations.CreateModel(
            name='a7Alianzas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Home/Alianza')),
            ],
            options={
                'verbose_name': 'Alianza',
                'verbose_name_plural': 'Alianzas',
            },
        ),
    ]
