# Generated by Django 4.1.7 on 2023-04-24 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicrosWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='a1promociones',
            options={'verbose_name': '01Promocion', 'verbose_name_plural': '01Promociones'},
        ),
        migrations.AlterModelOptions(
            name='a2productos',
            options={'verbose_name': '02Producto', 'verbose_name_plural': '02Productos'},
        ),
        migrations.AlterModelOptions(
            name='a3servicios',
            options={'verbose_name': '03Servicio', 'verbose_name_plural': '03Servicios'},
        ),
        migrations.AlterModelOptions(
            name='a4negocio',
            options={'verbose_name': '04Negocio', 'verbose_name_plural': '04Negocios'},
        ),
        migrations.AlterModelOptions(
            name='a5sifras',
            options={'verbose_name': '05Sifra', 'verbose_name_plural': '05Sifras'},
        ),
        migrations.AlterModelOptions(
            name='a6noticias',
            options={'verbose_name': '06Noticia', 'verbose_name_plural': '06Noticios'},
        ),
        migrations.AlterModelOptions(
            name='a7alianzas',
            options={'verbose_name': '07Alianza', 'verbose_name_plural': '07Alianzas'},
        ),
    ]
