# Generated by Django 4.1.7 on 2023-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicrosWeb', '0002_alter_a1promociones_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a1promociones',
            name='Contenido',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='a2productos',
            name='Contenido',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='a3servicios',
            name='Contenido',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='a4negocio',
            name='Contenido',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='a5sifras',
            name='Contenido',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='a6noticias',
            name='Contenido',
            field=models.TextField(max_length=5000),
        ),
    ]
